version: "3.7"

services:
  infra:
    build: 
      dockerfile: master.Dockerfile
    volumes:
      - ./ansible/:/root/
    command: tail -f /dev/null
    ports: 
     - "2220:22"

  front:
    build: 
      dockerfile: server.Dockerfile
    command: bash -c "service ssh start && tail -f /dev/null" 

  back:
    build: 
      dockerfile: server.Dockerfile
    command: bash -c "service ssh start && tail -f /dev/null" 

  db:
    build: 
      dockerfile: server.Dockerfile
    command: bash -c "service ssh start && tail -f /dev/null" 