---
- hosts: angular_vm
  tasks:
    - name: Install Node.js and npm
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nodejs
        - npm

    - name: Install Angular CLI
      npm:
        name: "@angular/cli"
        global: yes