---
- hosts: back
  become: true

  vars:
      ansible_become_password: ansible
      
  roles:
    - php
    - nginx_back
    - composer
    - env_back

    # Ajouter d'autres rôles ou tâches spécifiques au backend au besoin
